name: Build macOS duckdb.node

on:
  workflow_dispatch: # GitHub Actionsから手動実行できる

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Find macOS duckdb.node
        run: |
          find node_modules/duckdb/lib/binding -name "*.node"

      - name: Copy duckdb.node for packaging
        run: |
          mkdir -p duckdb-binaries/darwin-arm64
          cp node_modules/duckdb/lib/binding/Release/duckdb.node duckdb-binaries/darwin-arm64/duckdb-darwin-arm64.node

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: duckdb-darwin-arm64
          path: duckdb-binaries/darwin-arm64/duckdb-darwin-arm64.node
