name: build @duckdb/node-api on Multiple Platforms
# @duckdb/node-bindings-darwin-arm64  (macOS Apple Silicon)
# @duckdb/node-bindings-darwin-x64    (macOS Intel)
# @duckdb/node-bindings-linux-arm64   (Linux ARM64)
# @duckdb/node-bindings-linux-x64     (Linux x64)
# @duckdb/node-bindings-win32-x64     (Windows x64)

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # 各OSで自動的に正しいバイナリがインストールされる
      - run: npm install
